server:
  port: 80
  context-path: /

## 下面的数据库和redis需要填写你自己的

spring:
    datasource:
      url: jdbc:mysql://116.196.66.248:3306/db1?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password:
      driverClassName: com.mysql.jdbc.Driver

jedis:
  pool:
    host: 192.168.0.148
    password:
    port: 6379
    timeout: 2000
    config:
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis : 100000